### ISSUE TITLE
NPM install does not give a usable module to require

### ISSUE THREAD

**Issue by jeromecovington** [Modernizr/Modernizr#1623] opened 2015-07-31 02:06 UTC
We can:
```
npm install --save modernizr
```

It seems that we still need to:
```
./bin/modernizr
```

Before we can:
```
require('modernizr');
```

This seems odd within the npm ecosystem. Is there a better way?

**Comment by patrickkettner** [comment] 2015-07-31 02:34
in what way do you need to `./bin/modernizr` before you require it?

**Comment by jeromecovington** [comment] 2015-08-01 19:39
Do you not need to build modernizr within the its node_modules directory in order to then have a modernizr.js that can be required via node/CommonJS/Browserify?

**Comment by patrickkettner** [comment] 2015-08-01 19:41
Yes. The module is for the builder, not for the feature detects themselves.

**Comment by patrickkettner** [comment] 2015-08-01 19:41
Closing as AS DESIGNED

**Closed by patrickkettner** 2015-08-01 19:41 UTC

**Comment by jeromecovington** [comment] 2015-08-01 20:33
From my perspective, the `node_modules` dir of my app can/should be able to be a black box that does not need any more tinkering to allow my app to "just work" when somebody runs `npm install` within my project root, with "modernizer" listed in my `package.json` as a dependency. Ah well.

**Comment by patrickkettner** [comment] 2015-08-01 20:38
You are confusing the purpose of he module. It does just work - for its
intended purpose. A code generator. If you want to use modernizr as a
dependency for your front end code, then you should generate that
standalone file and check it in directly, rather than using an npm module.

**Comment by jeromecovington** [comment] 2015-08-01 21:49
Ok, thanks for clarifying. Personally I am working towards a future where all the dependencies of my project, both serverside and front end, can be managed within my `package.json`. Understood that is not the intended purposes of this module.

**Comment by patrickkettner** [comment] 2015-08-01 21:50
Good luck!

**Comment by g-borgulya** [comment] 2018-03-08 09:08
I understand now that this is "AS DESIGNED" but I think that doesn't necessarily mean that this design is a good idea. People manage their projects with npm, automate their builds and environments with docker and other useful tools. If this project doesn't follow the logic of these modern tools then it's likely that it is simply not worth using Modernizr for modern projects.

I'm not deeply understanding the core ideas behind Modernizr, I just know that I'd expect an npm package that could be a non-global dependency of my projects, and that could be used something like:
```js
import {passiveeventlisteners} from 'Modernizr'
```
If it's not like this then it seems to be easier if I write the feature checking myself than changing my development and production scripts to have Modernizr customized and built.

**Comment by patrickkettner** [comment] 2018-03-08 09:11
PRs are welcomed

**Comment by djibarian** [comment] 2019-02-11 10:55
Agree with the statements from @g-borgulya and @jeromecovington. I’m new to Modernizr and was expecting it to work as `import { feature } from Modernizr`. I’m too lazy to using it in a different way.

**Comment by niksy** [comment] 2019-02-12 08:18
@g-borgulya @jeromecovington @djibarian I’ve made this possible in my fork of Modernizr: https://github.com/niksy/modernizr-esm
