### ISSUE TITLE
CSS custom properties appears to be missing from docs and download builder

### ISSUE THREAD

**Issue by philwolstenholme** [Modernizr/Modernizr#2488] opened 2019-12-16 11:35 UTC
I can [see the custom properties test in the 3.8 codebase](https://github.com/Modernizr/Modernizr/blob/v3.8.0/feature-detects/css/customproperties.js) but it doesn't seem to be listed on https://modernizr.com/docs or in the builder.

**Comment by rejas** [comment] 2019-12-16 11:57
Yeah, i know :-) Website is outdated until further notice, sorry. Duplicate of https://github.com/Modernizr/modernizr-neue/issues/140

**Closed by rejas** 2019-12-16 11:57 UTC

**Comment by philwolstenholme** [comment] 2019-12-16 12:21
Ah, thanks for the info. I'm using the CLI now and it all looks okay 👍
