### ISSUE TITLE
On pageload HTML5 input element with autofocus losing focus 

### ISSUE THREAD

**Issue by gehlen** [Modernizr/Modernizr#1987] opened 2016-05-20 11:50 UTC
On pageload the function "test_hyphens_find" will unfocus an HTML5 input element with attribute autofocus.

Using 3.3.1 with all features..

**Comment by tomciopp** [comment] 2017-04-21 15:20
I can also confirm that this test breaks autofocus in forms. The solution is to remove the test but that kinda feels bad.

**Comment by patrickkettner** [comment] 2017-04-21 18:51
Another solution would be to do something like `const el = document.querySelector("[autofocus]"); el&&el.focus();` after the test runs. 

The detect itself could be updated to cache and refocus `document.activeElement` as well

**Comment by rejas** [comment] 2018-07-05 09:58
Duplicate of https://github.com/Modernizr/Modernizr/issues/1781 

Not sure if @patrickkettner solution is better than the PR https://github.com/Modernizr/Modernizr/pull/1633

**Closed** 2018-07-05 09:59 UTC
