### ISSUE TITLE
node-style/browserify compatible module output

### ISSUE THREAD

**Issue by gajus** [Modernizr/Modernizr#1527] opened 2015-02-17 09:17 UTC
The default build will export modernizr under the `window` namespace. It would be nice to have a build option that would use `module.exports` instead. As a dirty workaround, I have used:

```js
gulp.task('modernizr', ['lint'], function (cb) {
    var fs = require('fs'),
        modernizr = require('modernizr');

    modernizr.build({
        options: [],
       'feature-detects': [
            'touchevents'
        ]
    }, function (build) {
        build = build.replace('window.Modernizr = Modernizr', 'module.exports = Modernizr')

        fs.writeFile('./src/js/modernizr.js', build, cb);
    });
});
```

**Comment by patrickkettner** [comment] 2015-02-17 17:51
hey @gajus!

this is a actually a dupe of #1204, so I am going to close this one out

**Closed by patrickkettner** 2015-02-17 17:51 UTC
