### ISSUE TITLE
Add main value in bower.json

### ISSUE THREAD

**Issue by fr-olivier** [Modernizr/Modernizr#1491] opened 2015-01-15 15:44 UTC
Hello,

I guess I could make a pull request for this but it sounds too tricky for me, so I prefer asking:
Could you add a "main" value in bower.json please? I use it a lot in my build process to concat all the plugins I installed via bower (and inject them in php by the way).
So, the bower.json could look like this:
{
  "name": "modernizr",
  "homepage": "https://github.com/Modernizr/Modernizr",
  "version": "2.8.2",
  "_release": "2.8.2",
  "main": "modernizr.js",
  "_resolution": {
    "type": "version",
    "tag": "v2.8.2",
    "commit": "99c09fa23a83f160a021c98b3644628aaec5e37a"
  },
  "_source": "git://github.com/Modernizr/Modernizr.git",
  "_target": "2.8.2",
  "_originalSource": "modernizr"
}

Thanks a lot,
François

**Comment by patrickkettner** [comment] 2015-01-15 17:08
Hey François!
This is actually a dupe of #1334

have a great day!

**Closed by patrickkettner** 2015-01-15 17:08 UTC
