### ISSUE TITLE
Webpack + Modernizr?

### ISSUE THREAD

**Issue by Ncage1974** [Modernizr/Modernizr#2020] opened 2016-07-06 19:19 UTC
Did some googling around and didn't find a great answer. I found an issue from about a year ago but someone mentioned that webpack and moderizr should work together as of modernizr v3. 
Version Info:
modernizr: 3.3.1
webpack:  1.13.1
npm: 3.9.5
node: 6.2.2

Error when i try to require modernizr:
var Modernizr = require('modernizr');

ERROR in ./~/modernizr/lib/build.js
Module not found: Error: Cannot resolve module 'generate' in /home/brent/sandbox/WebPackTest/node_modules/modernizr/lib
 @ ./~/modernizr/lib/build.js 151:2-72

ERROR in ./~/modernizr/lib/build.js
Module not found: Error: Cannot resolve module 'lib/generate-banner' in /home/brent/sandbox/WebPackTest/node_modules/modernizr/lib
 @ ./~/modernizr/lib/build.js 151:2-72

ERROR in ./~/modernizr/lib/build.js
Module not found: Error: Cannot resolve module 'package' in /home/brent/sandbox/WebPackTest/node_modules/modernizr/lib
 @ ./~/modernizr/lib/build.js 151:2-72

ERROR in ./~/modernizr/lib/metadata.js
Module not found: Error: Cannot resolve module 'fs' in /home/brent/sandbox/WebPackTest/node_modules/modernizr/lib
 @ ./~/modernizr/lib/metadata.js 1:9-22

ERROR in ./~/modernizr/lib/options.js
Module not found: Error: Cannot resolve module 'fs' in /home/brent/sandbox/WebPackTest/node_modules/modernizr/lib
 @ ./~/modernizr/lib/options.js 1:9-22

ERROR in ./~/modernizr/package.json
Module parse failed: /home/brent/sandbox/WebPackTest/node_modules/modernizr/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp.raise (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.unexpected (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1490:8)
    at Parser.pp.semicolon (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1469:73)
    at Parser.pp.parseExpressionStatement (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1994:8)
    at Parser.pp.parseStatement (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1772:188)
    at Parser.pp.parseBlock (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:2009:21)
    at Parser.pp.parseStatement (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1753:19)
    at Parser.pp.parseTopLevel (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1666:21)
    at Parser.parse (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1632:17)
    at Object.parse (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/home/brent/sandbox/WebPackTest/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/home/brent/sandbox/WebPackTest/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.provide (/home/brent/sandbox/WebPackTest/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.readFile (/home/brent/sandbox/WebPackTest/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:140:24)
    at DependenciesBlock.onLoadPitchDone (/home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:255:7)
    at DependenciesBlock.loadPitch (/home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:182:27)
    at DependenciesBlock.doBuild (/home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at DependenciesBlock.build (/home/brent/sandbox/WebPackTest/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/home/brent/sandbox/WebPackTest/node_modules/webpack/lib/Compilation.js:126:9)
    at /home/brent/sandbox/WebPackTest/node_modules/webpack/lib/Compilation.js:309:10
    at /home/brent/sandbox/WebPackTest/node_modules/webpack/lib/NormalModuleFactory.js:58:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/home/brent/sandbox/WebPackTest/node_modules/tapable/lib/Tapable.js:75:69)
    at onDoneResolving (/home/brent/sandbox/WebPackTest/node_modules/webpack/lib/NormalModuleFactory.js:38:11)
    at onDoneResolving (/home/brent/sandbox/WebPackTest/node_modules/webpack/lib/NormalModuleFactory.js:121:6)
    at /home/brent/sandbox/WebPackTest/node_modules/webpack/lib/NormalModuleFactory.js:116:7
    at /home/brent/sandbox/WebPackTest/node_modules/async/lib/async.js:726:13
    at /home/brent/sandbox/WebPackTest/node_modules/async/lib/async.js:52:16
 @ ./~/modernizr/lib/build.js 135:12-38

ERROR in ./~/modernizr/lib/polyfills.json
Module parse failed: /home/brent/sandbox/WebPackTest/node_modules/modernizr/lib/polyfills.json Unexpected token (2:13)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:13)
    at Parser.pp.raise (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.unexpected (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1490:8)
    at Parser.pp.semicolon (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1469:73)
    at Parser.pp.parseExpressionStatement (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1994:8)
    at Parser.pp.parseStatement (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1772:188)
    at Parser.pp.parseBlock (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:2009:21)
    at Parser.pp.parseStatement (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1753:19)
    at Parser.pp.parseTopLevel (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1666:21)
    at Parser.parse (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1632:17)
    at Object.parse (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/home/brent/sandbox/WebPackTest/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/home/brent/sandbox/WebPackTest/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/brent/sandbox/WebPackTest/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/brent/sandbox/WebPackTest/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
 @ ./~/modernizr/lib/metadata.js 4:16-43

ERROR in ./~/requirejs/bin/r.js
Module parse failed: /home/brent/sandbox/WebPackTest/node_modules/requirejs/bin/r.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '#' (1:0)
    at Parser.pp.raise (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.getTokenFromCode (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:2831:8)
    at Parser.pp.readToken (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:2526:15)
    at Parser.pp.nextToken (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:2518:71)
    at Parser.parse (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1631:10)
    at Object.parse (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/home/brent/sandbox/WebPackTest/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/home/brent/sandbox/WebPackTest/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/brent/sandbox/WebPackTest/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/brent/sandbox/WebPackTest/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
 @ ./~/modernizr/lib/build.js 133:18-38

ERROR in ./~/file/lib/file.js
Module not found: Error: Cannot resolve module 'fs' in /home/brent/sandbox/WebPackTest/node_modules/file/lib
 @ ./~/file/lib/file.js 2:9-22

ERROR in ./~/doctrine/package.json
Module parse failed: /home/brent/sandbox/WebPackTest/node_modules/doctrine/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp.raise (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.unexpected (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1490:8)
    at Parser.pp.semicolon (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1469:73)
    at Parser.pp.parseExpressionStatement (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1994:8)
    at Parser.pp.parseStatement (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1772:188)
    at Parser.pp.parseBlock (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:2009:21)
    at Parser.pp.parseStatement (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1753:19)
    at Parser.pp.parseTopLevel (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1666:21)
    at Parser.parse (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:1632:17)
    at Object.parse (/home/brent/sandbox/WebPackTest/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/home/brent/sandbox/WebPackTest/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/home/brent/sandbox/WebPackTest/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.provide (/home/brent/sandbox/WebPackTest/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.readFile (/home/brent/sandbox/WebPackTest/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:140:24)
    at DependenciesBlock.onLoadPitchDone (/home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:255:7)
    at DependenciesBlock.loadPitch (/home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:182:27)
    at DependenciesBlock.doBuild (/home/brent/sandbox/WebPackTest/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at DependenciesBlock.build (/home/brent/sandbox/WebPackTest/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/home/brent/sandbox/WebPackTest/node_modules/webpack/lib/Compilation.js:126:9)
    at /home/brent/sandbox/WebPackTest/node_modules/webpack/lib/Compilation.js:309:10
    at /home/brent/sandbox/WebPackTest/node_modules/webpack/lib/NormalModuleFactory.js:58:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/home/brent/sandbox/WebPackTest/node_modules/tapable/lib/Tapable.js:75:69)
    at onDoneResolving (/home/brent/sandbox/WebPackTest/node_modules/webpack/lib/NormalModuleFactory.js:38:11)
    at onDoneResolving (/home/brent/sandbox/WebPackTest/node_modules/webpack/lib/NormalModuleFactory.js:121:6)
    at /home/brent/sandbox/WebPackTest/node_modules/webpack/lib/NormalModuleFactory.js:116:7
    at /home/brent/sandbox/WebPackTest/node_modules/async/lib/async.js:726:13
    at /home/brent/sandbox/WebPackTest/node_modules/async/lib/async.js:52:16
 @ ./~/doctrine/lib/utility.js 31:14-40

Should this be working as of now or is it on the doc to be fixed? Any workarounds?

**Comment by patrickkettner** [comment] 2016-07-12 08:14
closing as a dupe of #2012

if you check out the file you are including, it isn't a webpackable file. you will want to create a build using the nodecli or the website, then include _that_ as a static asset in your webpack build

**Closed by patrickkettner** 2016-07-12 08:14 UTC

**Comment by ryanseddon** [comment] 2016-07-13 00:12
You might want to check out this project https://github.com/peerigon/modernizr-loader
