### ISSUE TITLE
softhyphensfind bug

### ISSUE THREAD

**Issue by evilebottnawi** [Modernizr/Modernizr#1632] opened 2015-08-25 10:05 UTC
softhyphensfind test scroll on top body if page refresh in Google Chrome 44.0.2403.155 (64-bit)

**Comment by mkra** [comment] 2016-06-24 08:16
The problem still exists in version 3.3.1 in all browsers.

**Comment by rejas** [comment] 2018-07-02 20:35
Duplicate of #1781

**Closed by rejas** 2018-07-02 20:35 UTC
