### ISSUE TITLE
test for document.execCommand 

### ISSUE THREAD

**Issue by kobi-kadosh** [Modernizr/Modernizr#1733] opened 2015-10-27 14:55 UTC
Add document.execCommand test to detect if browser supports document.execCommand

https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

http://caniuse.com/#feat=document-execcommand

**Comment by patrickkettner** [comment] 2015-10-27 17:01
What browser doesn't? It's a super old API, no?

**Comment by kobi-kadosh** [comment] 2015-10-27 20:50
It isn't working on iOS 
This is the can i use http://caniuse.com/#feat=document-execcommand
My interest came from here https://zenorocha.github.io/clipboard.js/

**Comment by patrickkettner** [comment] 2015-10-27 20:55
actually, as noted in the caniuse link you referred to, it _has_ been supported since iOS 5. However execCommand !== programmatic copy support.

You are looking for a sniff for that, then this would be a dupe of #605 - basically, there is not a way to detect this currently.

**Closed by patrickkettner** 2015-10-27 20:55 UTC
