### ISSUE TITLE
Modernizr causes FOUC in Chrome 42+ if loaded in head

### ISSUE THREAD

**Issue by jkj** [Modernizr/Modernizr#1631] opened 2015-08-21 00:42 UTC
This took me a long time to diagnose but I proved it by slowly single stepping through the Modernizer code as it loaded. When loaded in the head element, as opposed to the very end of the body, Modernizer causes a FOUC* in Chrome 42 and above. It doesn't seem to do this with Firefox, IE 11 or Edge. I have not tested with Safari. An example of this FOUC in action can be seen by visiting, for example, foundation.zurb.com. It doesn't *always* show up but here is a video that clearly exhibits the problem: https://drive.google.com/open?id=0B5QSVOs89Uu9cHdXZjBqMmczdUE&authuser=0

I originally thought this was a Foundation bug but I have determined that it is really Modernizr. What happens is that when Modernizr is loaded in the head, as it does various tests, in `injectElementWithStyles` it creates a body if none exists. This causes Chrome to render an empty body. If no CSS has been loaded prior to Modernizr, then the empty body is white. On my particular site where the base background colour is blue, this quick flash of white is very unsightly. By setting the body colour to blue before loading Modernizer it reduces the "glaringness" of the FOUC but it still causes an empty page to be displayed very briefly before the real body is loaded. Thus as a user moves from page to page the screen appears to "flash". Moving the load of Modernizr down to the end of the body to just before I load jQuery and Foundation fixes the problem but I have seen numerous people suggest that Modernizr really should be loaded in the head, right before the main CSS file. At the very least I think that should be supported without side effects.

*I use the term FOUC here because it has the visual appearance of a FOUC error, not because it is an actual flash of unstyled content. Rather it is a "flash of an empty body using the browsers default body styling if no other body styling has been loaded yet".

**Comment by patrickkettner** [comment] 2015-08-23 05:26
Hey @jkj!

I am not really sure what the issue here is. Websites have a white background at least until the css is parsed and it is changed. Your video just looks like a website reloading to me. :/

Outside of that, wether or not Modernizr should be loaded in the head is really up to the end developer. Ironically the main reason why its recommended to be in the head is to avoid a FOUC (e.g. when the page uses Modernizr classes to style the page). If it doesn't make sense for you to have it there - don't put it there. 

Finally, if you _need_ to load it in the head, you can inline the critical css above the Modernizr instantiation. If its just the body background color that is startling, then a one line style tag above the script file should be enough to take care of it. 

I do apologize if I am being thick or misunderstanding the issue - please do let me know if that is the case

**Comment by jkj** [comment] 2015-08-23 06:25
Not being thick at all but perhaps I didn't explain it well. In every browser other than Chrome, and even in Chrome in all versions prior to 42, that white flash you see in the video is not present. If you have a site that has a pretty constant head - for example always the same top bar, possibly a logo or something ... but some static content at the top, that flash redraw is pretty unsightly. Using just Firefox as an example, lets say I navigate from page A to page B on the site. The top elements do not appear to change at all and the transition is very fluid. I suspect this has to do with how the redrawing takes place - that it doesn't actually clear the body to a blank page but rather those elements that were unchanged in appearance and position in the header don;t get redrawn. The same is true of Chrome 42+ if you put Modernizr at the end of the body. That flash of an empty body makes the whole page "blink" when moving from page A to B. In all other browsers that transition is absolutely seemless.

I have already inlined critical CSS before modernizer, for example to set the body background to blue. I guess my question is this. In `injectElementWithStyles` does it *have* to inject a body element? Would it be possible to use some other tag that won't cause an actual screen redraw? For example in a non-standard tag like <modernizr> or something? I know that does not conform to the standard but if it doesn't break the tests it may fix the problem. I will play around with it some and let you know what I find. Thank you for the response.

**Comment by patrickkettner** [comment] 2015-08-23 06:28
> In injectElementWithStyles does it have to inject a body element

yes

> For example in a non-standard tag like or something

not in older browsers, which are the ones that generally need the most feature detection :/

For now, this is more or less a won't fix since there are many ways around this problem (e.g. moving modernizr later in the DOM, inlining css, etc). On top of that, it is only showing up in Chrome. I really hope that you keep digging and either report the issue to Chrome to see if they can fix the regression of sorts, or figure out a way to update the tests to not use the boy tag (which I have never been able to do myself).

good luck and godspeed, my friend

**Closed by patrickkettner** 2015-08-23 06:28 UTC
