### ISSUE TITLE
Modernizr.localizednumber moves head below body

### ISSUE THREAD

**Issue by Nettsentrisk** [Modernizr/Modernizr#1836] opened 2016-01-14 16:34 UTC
I randomly noticed that when running an unminified full build version of Modernizr 3.3.0, the DOM was being changed so that the head element was ending up below body.

I've narrowed it down to the localizednumber test, and its setting of the root variable.

Probably not a big problem, but I doubt that this is intended.

**Comment by patrickkettner** [comment] 2016-01-14 18:41
Hey @Nettsentrisk! can you show a demo page?

**Comment by Nettsentrisk** [comment] 2016-01-15 10:18
Sure, here's a CodePen with a Modernizr build with only the localizednumber test active (unminified): http://codepen.io/anon/pen/Bjwjxq

**Comment by Ballrock** [comment] 2018-02-22 08:42
Hey, got the same problem.
When body.fake = undefined, head and body don't switch back their positions.

In my test, the problem seems to occur when modernizr is include at the bottom of body instead of being include in head. 
Body is already render so getBody() return real body and body.fake = undefined.

Looks like a side effect and i dont think it was intended

**Comment by SurajVerma** [comment] 2018-08-08 15:58
This issue still exists, using dev build 3.6.0 unminified version. <head> element moves below <body> element.

**Comment by SurajVerma** [comment] 2018-08-08 16:01
This issue still exists, using dev build 3.6.0 unminified version. `<head>` element moves below `<body> `element. In my case, issue persist even if I remove localizednumber test. :(

**Comment by rejas** [comment] 2018-08-09 10:16
Hi @SurajVerma could you post your config that you used to build he modenrizr js so we can try to reproduce it?

**Comment by SurajVerma** [comment] 2018-08-09 11:36
Hi @rejas :)
I am using the raw development build as it is from. Removing input[type="number"] Localization test fixes the problem for me as well. 

Head with number localization test in modernizr
![head-b](https://user-images.githubusercontent.com/5441349/43896437-6962527e-9bf6-11e8-827a-7a49863034eb.PNG)

Head without number localization test in modernizr
![head-a](https://user-images.githubusercontent.com/5441349/43896451-77125b76-9bf6-11e8-9bc4-264b21875083.PNG)


Here is the codepen link to raw build I am using. https://codepen.io/SurajVerma/pen/RBqOyB

**Comment by rejas** [comment] 2018-08-10 14:18
Opened a PR with a fix for this issue, hope it gets though the review of @patrickkettner :-)

**Closed** 2018-08-13 16:19 UTC
