### ISSUE TITLE
Windows - Error: Tried loading "src/generate.js"

### ISSUE THREAD

**Issue by mahnunchik** [Modernizr/Modernizr#1524] opened 2015-02-12 14:23 UTC
Hi,

I think it is related to Modernizr core: https://github.com/doctyper/gulp-modernizr/issues/23

```
C:\project>gulp modernizr
[06:07:25] Using gulpfile C:\project\gulpfile.js
[06:07:25] Starting 'modernizr'...
C:\project\node_modules\gulp-modernizr\node_modules\custom
izr\node_modules\modernizr\node_modules\requirejs\bin\r.js:2559
                    throw err;
                          ^
Error: Tried loading "src/generate.js" at src/generate.js then tried node's require("src/generate.js") and it failed with error: Error: Cannot find module 'src/generate.js'
    at C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:2552:27
    at Object.context.execCb (C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:1916:33)
    at Object.Module.check (C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:1125:51)
    at Object.Module.enable (C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:1409:22)
    at Object.context.enable (C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:1777:39)
    at Function.req.get (C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:2476:33)
    at Object.localRequire [as require] (C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:1650:40)
    at requirejs (C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\node_modules\requirejs\bin\r.js:2003:24)
    at Object.<anonymous> (C:\project\node_modules\gulp-modernizr\node_modules\customizr\node_modules\modernizr\lib\build.js:123:18)
    at Module._compile (module.js:460:26)

C:\project>
```

**Comment by owanturist** [comment] 2015-02-12 14:38
:+1:

**Comment by patrickkettner** [comment] 2015-02-12 16:24
Duplicate of 1523

**Closed by patrickkettner** 2015-02-12 16:24 UTC
